### ISSUE TITLE
Someone hit the webhook for 'xxx' and it failed to validate.

### ISSUE THREAD

**Issue by chevett** [Strider-CD/strider-github#10]
Strider was really easy to get mostly working!  The only issue I'm having is that web hooks from github aren't validating and therefore aren't triggering builds.

I have a server running strider on http://localhost:3000 then I have nginx in front of that handling the ssl at https://ci.miketown3.com.

I'm trying to get notifications from https://github.com/rrrelay/named-logger and it's setup to hit `https://ci.miketown3.com/rrrelay/named-logger/api/github/webhook`.

In the strider logs, I see
```
 warn: Someone hit the webhook for rrrelay/named-logger and it failed to validate
POST /rrrelay/named-logger/api/github/webhook 401 55ms - 17b
````

I've been testing the webhook from the github page and it looks like this...
![2014-03-16_2059](https://f.cloud.github.com/assets/1141615/2432732/180dcdfe-ad71-11e3-98d5-4ffd62b51ff5.png)

I've also created a new github application and set the env variables  PLUGIN_GITHUB_APP_ID and  PLUGIN_GITHUB_SECRET to the  client id and client secret.

Is the payload missing the x-hub-signature header or something?  Any help/ideas would be greatly appreciated!  Thanks!

**Comment by knownasilya** [comment]
@chevett I'm assuming this is still an issue even with the current master version?

**Comment by chevett** [comment]
I haven't updated in a while, but I can give it a try this afternoon if
that's helpful.

**Comment by knownasilya** [comment]
@chevett would be much appreciated! :+1:

**Comment by chevett** [comment]
There isn't much of an issue here anymore.  There was a bug in the github ui that messed up the webhook if you disabled the ssl verification and I have just confirmed that this bug has been fixed by github.

If you have a strider instance that is using a self signed cert, then you have manually disable ssl verification through the github webhook ui and that is working correctly now.
