### ISSUE TITLE
The redirect_uri MUST match the registered callback

### ISSUE THREAD

**Issue by reiven** [Strider-CD/strider-github#34]
Hi

I'm running strider on port 7777, i've set this ENV variables:
> export PORT=7777
> export SERVER_NAME="http://my.server.ip.address"
> export PLUGIN_GITHUB_APP_ID="hereComesTheId"
> export PLUGIN_GITHUB_APP_SECRET="theSecretFromGithub"
> export PLUGIN_GITHUB_HOSTNAME="http://my.server.ip.address"
> export STRIDER_HOSTNAME="http://my.server.ip.address"

on github, if i set the callback to
> http://my.server.ip.address:7777/auth/github/callback
it says: 500 AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.

What i'm doing wrong?

**Comment by knownasilya** [comment]
I think you need to specify the port in your `SERVER_NAME` variable.

**Comment by reiven** [comment]
@knownasilya thanks for you answer, that was fast :)
anyway, now i got
> 500 TypeError: Cannot read property '0' of undefined
but i have email set on github (!?)

**Comment by knownasilya** [comment]
You need to add your email to github. Also, make sure to update your github plugin via the plugin manager.

**Comment by reiven** [comment]
Ok, i've already had an email address but what is needed is to have a public email email on your profile. 
It will be nice to add this settings in the Readme :)

Thanks a lot @knownasilya !

**Comment by knownasilya** [comment]
No problem, feel free to submit a PR to cleanup the README :+1:
