### ISSUE TITLE
Not sure how to install this alongside Strider itself

### ISSUE THREAD

**Issue by notbrain** [Strider-CD/strider-github#37]
Been reading all the READMEs and a little bit of the code but can't find a step by step on how to install strider-github alongside strider itself. Is it a standalone server? Where does it go? I tried

    $ bin/strider install strider-github
    GET [ecosystem]/plugins.yml
    strider-github is not a valid plugin

Any guidance greatly appreciated!

**Comment by knownasilya** [comment]
should just be `bin/strider install github` since it looks by the id in the index, here: https://github.com/Strider-CD/ecosystem-index/blob/master/plugins.yml

But really, you can do all of this through the UI. Admin > Plugins > Update all plugins, then install additional plugins.

**Comment by notbrain** [comment]
Thanks!
