### ISSUE TITLE
Please update version on npm to 2.2.0

### ISSUE THREAD

**Issue by mastertinner** [Strider-CD/strider-github#58]

**Comment by alexfernandez** [comment]
Yes, please! 2.1.2 is not working for me, always uses `localhost:3000`.

**Comment by knownasilya** [comment]
Published. @alexfernandez are you setting your `SERVER_NAME` and `PLUGIN_*` envs?

**Comment by alexfernandez** [comment]
Wow that was quick :)

Yes, I am adding `SERVER_NAME`, but it was not working with @2.1.2. I am unhappy to report that it is not working either with @2.2.0. I will comment on the relevant issue https://github.com/Strider-CD/strider-github/issues/55.

**Comment by knownasilya** [comment]
@alexfernandez are you adding the `PLUGIN_GITHUB_*` envs, you need those for Strider to recognize that you have a github plugin.

**Comment by alexfernandez** [comment]
Yes, those two too.
