### ISSUE TITLE
Setting up a private project I can access but do not own

### ISSUE THREAD

**Issue by alexfernandez** [Strider-CD/strider-github#60]
Using `strider-github@2.2.0`. In the list of projects I see all GitHub projects where I have access rights. However, when clicking on `Add` and while `Setting up` is running, I get an error:

    Error creating project for repo user/project:
    {"results":[],"status":"error","errors":[{"code":500,
    "reason":"Failed to setup repo: Bad status code: 404"}]}

If I fork the project then I can set it up, no problem. Is this how the plugin is supposed to work? Why can it list the projects but not add them?

**Comment by knownasilya** [comment]
You need to be the admin on the project, since Strider sets up webhooks.

**Comment by alexfernandez** [comment]
Oh, true. I think better documentation and error messages would solve the issue beautifully. Would you like me to send a PR with both?

**Comment by knownasilya** [comment]
@alexfernandez yes please :+1:
