### ISSUE TITLE
Use SSH authentication instead of HTTPS

### ISSUE THREAD

**Issue by mandoz** [Strider-CD/strider-github#68]
Hello,

I am running into a problem with the following situation:
I have a python project on github that depends other private repositories within the organization. When I run the tests using the docker runner, the repository is cloned using https authentication and no private key is used (and hence no private key is placed inside the repository). The way we install the dependencies would be by calling: 
```
pip install -e git+ssh://git@github.com/organization/repository.git@master#egg=repository
```
This would of course fail because this requires the private key.

If we switch authentication to ssh, this will force the private key to be put on the machine and used for all github communication (because of this: https://github.com/chriz2600/strider-docker-gitane-camo/blob/master/index.js#L15).

Best Regards,
Mohannad

**Comment by mandoz** [comment]
This is of course not specific to python per se, but to the use case of requiring private dependencies over `git+ssh`.

**Comment by mandoz** [comment]
If you have an existing installation of Strider-CD, you will need to do the following steps after the plugin upgrade:
1. Remove your project/repo.
2. Refresh your github repos.
3. Add the project/repo again.

This is because the value of the authentication method is set at the time the repos are fetched from github.

**Comment by knownasilya** [comment]
Might be easier to just update the mongodb table.
