### ISSUE TITLE
Strider build 'undefined' branch when tag is pushed

### ISSUE THREAD

**Issue by BluSyn** [Strider-CD/strider-github#74]
Recent strider + plugin upgrade caused this error. Have not yet determined what caused the breaking change.

When I push a new tag to my repo, strider attempts to build it, but `<%= ref.branch %>` returns `undefined`. Previously, strider would only build on branch pushes and not on new tags.

It's also possible this was a change in Github's webooks, but I haven't confirmed that. I tried disabling the 'Create' webhook event (Only 'Pull Request' and 'Push' options set), and it still sends a webhook and attempts to build it.

Note: This is causing some havoc with my build scripts, which expect a valid branch name. I've had to add checks for `undefined` branch in all build scripts so it doesn't cause deployment problems.

<img width="504" alt="screen shot 2016-10-25 at 11 35 30 am" src="https://cloud.githubusercontent.com/assets/535381/19699277/9684d544-9aa7-11e6-9542-f174113376d6.png">
<img width="531" alt="screen shot 2016-10-25 at 11 35 49 am" src="https://cloud.githubusercontent.com/assets/535381/19699285/9b8babee-9aa7-11e6-8a45-8582a663c94a.png">

**Comment by knownasilya** [comment]
Weird, I've experienced the opposite. In the past it would build on tag, but recently (with latest updated) it hasn't triggered on tags.

**Comment by BluSyn** [comment]
Strange. That's the problem I would prefer to have ;)

I usually push a tag+branch at the same time, and I don't recall it building twice in that case. Now it creates two builds: one with branch name, one `undefined`.

Version info-
Strider v1.9.3
strider-github v2.3.2

Screenshot shows how it looks in build history (tag+branch push):
<img width="461" alt="screen shot 2016-10-25 at 12 02 25 pm" src="https://cloud.githubusercontent.com/assets/535381/19700134/f491b0a0-9aaa-11e6-848e-ea2b478aa36a.png">

**Comment by anddimario** [comment]
I'm trying to use tags or release to trigger customs script, but triggers seems that are not fired. I saw that branch is undefined when hook is grabbed from strider, maybe it could be the problem. Have you some suggestions on this problem?

**Comment by BluSyn** [comment]
It appears this is fixed now. I think it was an issue with Github sending improper/multiple webhooks, and strider interpreting it incorrectly. I do not see this issue now.
