### ISSUE TITLE
Webhook error on release

### ISSUE THREAD

**Issue by anddimario** [Strider-CD/strider-github#76]
Hi, if i added a hook on releases the plugin crash, it seems that it search for commits, but the git payload doesn't have it, here the error:

> 0|strider  | 2016-11-21T15:11:43.877Z - error: TypeError: Cannot read property 'length' of undefined
0|strider  |     at startFromCommit (/home/strider/strider/node_modules/strider-github/lib/webhooks.js:50:51)
0|strider  |     at receiveWebhook (/home/strider/strider/node_modules/strider-github/lib/webhooks.js:277:16)
0|strider  |     at Layer.handle [as handle_request] (/home/strider/strider/node_modules/express/lib/router/layer.js:95:5)
0|strider  |     at next (/home/strider/strider/node_modules/express/lib/router/route.js:131:13)
0|strider  |     at projectProvider (/home/strider/strider/lib/middleware.js:118:3)
0|strider  |     at Layer.handle [as handle_request] (/home/strider/strider/node_modules/express/lib/router/layer.js:95:5)
0|strider  |     at next (/home/strider/strider/node_modules/express/lib/router/route.js:131:13)
0|strider  |     at /home/strider/strider/lib/middleware.js:234:7
0|strider  |     at /home/strider/strider/node_modules/mongoose/lib/query.js:2257:18
0|strider  |     at tryCatcher (/home/strider/strider/node_modules/bluebird/js/release/util.js:16:23)
0|strider  |     at Promise._settlePromiseFromHandler (/home/strider/strider/node_modules/bluebird/js/release/promise.js:510:31)
0|strider  |     at Promise._settlePromise (/home/strider/strider/node_modules/bluebird/js/release/promise.js:567:18)
0|strider  |     at Promise._settlePromise0 (/home/strider/strider/node_modules/bluebird/js/release/promise.js:612:10)
0|strider  |     at Promise._settlePromises (/home/strider/strider/node_modules/bluebird/js/release/promise.js:691:18)
0|strider  |     at Async._drainQueue (/home/strider/strider/node_modules/bluebird/js/release/async.js:138:16)
0|strider  |     at Async._drainQueues (/home/strider/strider/node_modules/bluebird/js/release/async.js:148:10)
0|strider  |     at Immediate.Async.drainQueues [as _onImmediate] (/home/strider/strider/node_modules/bluebird/js/release/async.js:17:14)

**Comment by knownasilya** [comment]
Released a new version, 2.3.3. Update in you plugins page.

**Comment by knownasilya** [comment]
Did 2.3.3 solve this issue?
