### ISSUE TITLE
Question: Do you need an email address for Github to work?

### ISSUE THREAD

**Issue by mishfit** [Strider-CD/strider-github#80]
This line seems to throw if I don't have a public email displayed on my profile, however, I have two invisible emails setup:

https://github.com/Strider-CD/strider-github/blob/master/lib/webapp.js#L169
```js
if (!profile.emails || !profile.emails.length)
```

What's more, the next line at which an email is used potentially doesn't care if you do have one or not:
https://github.com/Strider-CD/strider-github/blob/master/lib/webapp.js#L181
```js
mail: profile.emails ? profile.emails[0].value : null,
```

_**So should one have a public email or not?**_

_obviously one of these lines needs to change_

**Comment by knownasilya** [comment]
That is correct, you need a public email.
